name: Container Integration Test

on:
  pull_request:
  workflow_dispatch:

jobs:
  container-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build image (load into local docker)
        uses: docker/build-push-action@v6
        with:
          context: .
          push: false
          load: true
          platforms: linux/amd64
          tags: local/breitband:ci

      - name: Prepare CI config (disable mail/mqtt)
        run: |
          cat > "$GITHUB_WORKSPACE/config-ci.json" <<'JSON'
          {
            "mailer": { "enabled": false, "sendStatus": false },
            "mqtt": { "enabled": false }
          }
          JSON

      - name: Ensure export dir
        run: mkdir -p "$GITHUB_WORKSPACE/export"

      - name: Run container and capture logs
        run: |
          set -o pipefail
          docker run --rm \
            -e INTERVAL_MINUTES=0 \
            -e START_HEADLESS=true \
            -e EXPORT_PATH=/export \
            -e CONFIG_PATH=/usr/src/app/config.json \
            -v "$GITHUB_WORKSPACE/export":/export \
            -v "$GITHUB_WORKSPACE/config-ci.json":/usr/src/app/config.json:ro \
            local/breitband:ci 2>&1 | tee container.log || true

          # Patterns that indicate fatal failures we want to catch
          FATAL_PATTERNS=
          "EPERM: operation not permitted|EACCES: permission denied|chmod \'/export\'|Error starting puppeteer|Could not find Chrome|Failed to launch the browser process|UnhandledPromiseRejection|ERR_MODULE_NOT_FOUND|fatal error|uncaughtException|segmentation fault|panic|Error: Could not find Chrome|Error: Failed to launch the browser process"

          if grep -iE "$FATAL_PATTERNS" container.log >/dev/null 2>&1; then
            echo "ERROR: Fatal issue detected in container logs (matching patterns)."
            echo "---- container.log (tail) ----"
            tail -n 400 container.log
            exit 1
          fi

          # Also fail fast on common node rejection messages
          if grep -iE "unhandled promise rejection|unhandledRejection|Unhandled promise rejection" container.log >/dev/null 2>&1; then
            echo "ERROR: Unhandled promise rejection detected in container logs."
            tail -n 400 container.log
            exit 1
          fi

          # Quick checks for successful test completion
          if ! grep -q -i "Speedtest finished\|SPEEDTEST DONE\|Speedtest done\|saved results to" container.log; then
            echo "ERROR: Speedtest did not finish (no success marker in logs)"
            tail -n 400 container.log
            exit 1
          fi

          if ! ls "$GITHUB_WORKSPACE"/export/*.csv >/dev/null 2>&1; then
            echo "ERROR: No CSV file produced in export/"
            ls -la "$GITHUB_WORKSPACE"/export || true
            exit 1
          fi

      - name: Upload logs and export files
        uses: actions/upload-artifact@v4
        with:
          name: container-integration-results
          path: |
            container.log
            export