name: Container Integration Test

on:
  pull_request:
  workflow_dispatch:

jobs:
  container-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build image (load into local docker)
        uses: docker/build-push-action@v6
        with:
          context: .
          push: false
          load: true
          platforms: linux/amd64
          tags: local/breitband:ci

      - name: Make test script executable
        run: chmod +x .github/scripts/container-test.sh

      - name: Run container test script
        run: ./.github/scripts/container-test.sh local/breitband:ci