name: Build and Push Docker Image

on:
  push:
    branches: [ "main" ]

jobs:
  docker:
    environment: prod
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Read version from package.json
        id: version
        run: echo "version=$(node -p "require('./package.json').version")" >> $GITHUB_OUTPUT

      - name: Read yarn version from package.json
        id: yarn
        run: |
          node -e "const p=require('./package.json'); const m=p.packageManager||''; const v=(m.match(/yarn@([0-9]+\.[0-9]+\.[0-9]+)/)||[])[1]||'4.10.3'; console.log('yarn='+v)" >> $GITHUB_OUTPUT

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          build-args: |
            APP_VERSION=${{ steps.version.outputs.version }}
            YARN_VERSION=${{ steps.yarn.outputs.yarn }}
          tags: |
            shentoza/breitband-bna-tracker:${{ steps.version.outputs.version }}
            shentoza/breitband-bna-tracker:${{ github.sha }}
            shentoza/breitband-bna-tracker:latest
          cache-from: type=registry,ref=shentoza/breitband-bna-tracker:buildcache
          cache-to: type=registry,ref=shentoza/breitband-bna-tracker:buildcache,mode=max
